<a href="https://colab.research.google.com/github/tarun1208/BasicML/blob/main/Assignement1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Perform arithmetic operations on NumPy arrays.

In [ ]:
import numpy as np
arr1= np.array([10,20,30,40])
arr2= np.array([2,5,9,4])

#Addition
print(arr1+arr2)
print('-------------------------------------------')

#Subtraction
print(arr1-arr2)

print('-------------------------------------------')
#Multiplication
print(arr1*arr2)

print('-------------------------------------------')

#Division
print(arr1/arr2)
print('-------------------------------------------')

#Modular Division
print(arr1%arr2)

[12 25 39 44]
-------------------------------------------
[ 8 15 21 36]
-------------------------------------------
[ 20 100 270 160]
-------------------------------------------
[ 5.          4.          3.33333333 10.        ]
-------------------------------------------
[0 0 3 0]


Q2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
import numpy as np

arr=np.array([10,20,30,40])

#Mean
print(np.mean(arr))

#Standard Deviation
print(np.std(arr))

25.0
11.180339887498949


Q3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
import numpy as np

arr=np.arange(10, 51, 5)

print(arr)

[10 15 20 25 30 35 40 45 50]


Q4. Reshape the array into a 2x4 matrix.

In [ ]:
import numpy as np

arr=np.arange(10, 51, 5)
print(arr)

#Reshape
a = print(arr.reshape(3,3))

[10 15 20 25 30 35 40 45 50]
[[10 15 20]
 [25 30 35]
 [40 45 50]]
None


Q5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

• Extract the sub-matrix containing the last two rows and first two columns

• Replace all elements greater than 4 with 0.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the sub-matrix containing the last two rows and first two columns
print(arr[1:, :2])
print('-------------------------------------------')

#Extract the sub-matrix containing the last two rows and first two columns
arr[arr > 4] = 0
print(arr)


[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


Q6. Create two 1D arrays:

• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Addition
for i in range(len(a)):
  print(a[i]+b[i])
print('-------------------------------------------')

#Multiplication
for i in range(len(a)):
  print(a[i]*b[i])
print('-------------------------------------------')

#Division
for i in range(len(a)):
  print(a[i]/b[i])

5
7
9
-------------------------------------------
4
10
18
-------------------------------------------
0.25
0.4
0.5


Q7. Create a random NumPy array of size (4, 4). Compute:

• Mean of each column.

• Maximum value of the entire array.

In [ ]:
import numpy as np

#Random Array
arr = np.random.rand(4,4)
print(arr)
print('-------------------------------------------')

#Mean of each column.
print(np.mean(arr, axis=0))
print('-------------------------------------------')

#Maximum value of the entire array.
print(np.max(arr))

[[0.07835354 0.0772939  0.2184954  0.90657463]
 [0.83966391 0.6961681  0.26702701 0.21997265]
 [0.13620955 0.3949417  0.84384857 0.30419065]
 [0.27545254 0.99817253 0.54300208 0.39912364]]
-------------------------------------------
[0.33241989 0.54164406 0.46809327 0.45746539]
-------------------------------------------
0.9981725328746023


Q8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

#a=arr+10
#print(a*2)
print((arr+10)*2)

[22 24 26 28]


Q9. Perform advanced slicing and indexing on a 3D array.

Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1

In [ ]:
import numpy as np

#Creatinr 3D array of shape(3,4,5) with range from 1 to 100
arr = np.random.randint(1,101, size=(3,4,5))
print(arr)
print('-------------------------------------------')

#first two row last three columns
print(arr[: , :2, -3:])
print('-------------------------------------------')

#replace all elements divisible by 3 with -1
arr[arr%3==0] = -1
print(arr)

[[[ 33   3  56  87  24]
  [ 45  50  58  75  95]
  [ 16  70   5  89  73]
  [ 34  55  92  22   5]]

 [[ 13   7  41  52  27]
  [ 29  50  11  97  42]
  [ 30  86  66  60   3]
  [ 25  27   4  25  31]]

 [[  2   3  23  45  89]
  [ 48  15  30  41  25]
  [100  71  99  26  80]
  [ 97  99  18  56  53]]]
-------------------------------------------
[[[56 87 24]
  [58 75 95]]

 [[41 52 27]
  [11 97 42]]

 [[23 45 89]
  [30 41 25]]]
-------------------------------------------
[[[ -1  -1  56  -1  -1]
  [ -1  50  58  -1  95]
  [ 16  70   5  89  73]
  [ 34  55  92  22   5]]

 [[ 13   7  41  52  -1]
  [ 29  50  11  97  -1]
  [ -1  86  -1  -1  -1]
  [ 25  -1   4  25  31]]

 [[  2  -1  23  -1  89]
  [ -1  -1  -1  41  25]
  [100  71  -1  26  80]
  [ 97  -1  -1  56  53]]]


Q10. Work with broadcasting and advanced operations in NumPy.

Create a NumPy array arr of shape (3, 3) with random integers between  1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire array.

In [ ]:
import numpy as np

#Random Array of shape(3,3) with range 1 to 21
arr=np.random.randint(1 , 21, size=(3,3))
print(arr)
print('-------------------------------------------')

# Subtract the mean of each row from its respective elements (row-wise normalization).
for i in range(len(arr)):
  print(arr[i]-np.mean(arr[i]))
print('-------------------------------------------')

#Create a new array by squaring all the elements in arr.
print(np.square(arr))
print('-------------------------------------------')

# Find the indices of the top 3 maximum values in the entire array.
indices = np.argpartition(arr.flatten(), -3)[-3:]
row_indices, col_indices = np.unravel_index(indices, arr.shape)
print("Indices of top 3 maximum values:")
for i in range(3):
  print(f"Value: {arr[row_indices[i], col_indices[i]]}, Index: ({row_indices[i]}, {col_indices[i]})")

[[ 9 20  7]
 [16  6 13]
 [ 5  8  3]]
-------------------------------------------
[-3.  8. -5.]
[ 4.33333333 -5.66666667  1.33333333]
[-0.33333333  2.66666667 -2.33333333]
-------------------------------------------
[[ 81 400  49]
 [256  36 169]
 [ 25  64   9]]
-------------------------------------------
Indices of top 3 maximum values:
Value: 13, Index: (1, 2)
Value: 20, Index: (0, 1)
Value: 16, Index: (1, 0)
