<a href="https://colab.research.google.com/github/tarun1208/BasicML/blob/main/Assignement1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Perform arithmetic operations on NumPy arrays.

In [2]:
import numpy as np
arr1= np.array([10,20,30,40])
arr2= np.array([2,5,9,4])

#Addition
print(arr1+arr2)

#Subtraction
print(arr1-arr2)

#Multiplication
print(arr1*arr2)

#Division
print(arr1/arr2)

#Modular Division
print(arr1%arr2)

[12 25 39 44]
[ 8 15 21 36]
[ 20 100 270 160]
[ 5.          4.          3.33333333 10.        ]
[0 0 3 0]


Q2. Write a script to compute the mean and standard deviation of a NumPy array.

In [3]:
import numpy as np

arr=np.array([10,20,30,40])

#Mean
print(np.mean(arr))

#Standard Deviation
print(np.std(arr))

25.0
11.180339887498949


Q3. Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [6]:
import numpy as np

arr=np.arange(10, 51, 5)

print(arr)

[10 15 20 25 30 35 40 45 50]


Q4. Reshape the array into a 2x4 matrix.

In [13]:
import numpy as np

arr=np.arange(10, 51, 5)
print(arr)

#Reshape
a = print(arr.reshape(3,3))

[10 15 20 25 30 35 40 45 50]
[[10 15 20]
 [25 30 35]
 [40 45 50]]
None


Q5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

• Extract the sub-matrix containing the last two rows and first two columns

• Replace all elements greater than 4 with 0.

In [17]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the sub-matrix containing the last two rows and first two columns
print(arr[1:, :2])

#Extract the sub-matrix containing the last two rows and first two columns
arr[arr > 4] = 0
print(arr)


[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


Q6. Create two 1D arrays:

• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [21]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Addition
for i in range(len(a)):
  print(a[i]+b[i])

#Multiplication
for i in range(len(a)):
  print(a[i]*b[i])

#Division
for i in range(len(a)):
  print(a[i]/b[i])

5
7
9
4
10
18
0.25
0.4
0.5


Q7. Create a random NumPy array of size (4, 4). Compute:

• Mean of each column.

• Maximum value of the entire array.

In [23]:
import numpy as np

#Random Array
arr = np.random.rand(4,4)
print(arr)

#Mean of each column.
print(np.mean(arr, axis=0))

#Maximum value of the entire array.
print(np.max(arr))

[[0.63896397 0.9753155  0.57742455 0.14309763]
 [0.87106722 0.57753251 0.01814233 0.02338779]
 [0.59288166 0.36514895 0.3297117  0.07053596]
 [0.79508291 0.66377239 0.70467673 0.29829651]]
[0.72449894 0.64544234 0.40748883 0.13382947]
0.9753154961759959


Q8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4])

#a=arr+10
#print(a*2)
print((arr+10)*2)

[22 24 26 28]


Q9. Perform advanced slicing and indexing on a 3D array.

Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1

In [30]:
import numpy as np

#Creatinr 3D array of shape(3,4,5) with range from 1 to 100
arr = np.random.randint(1,101, size=(3,4,5))
print(arr)

#first two row last three columns
print(arr[: , :2, -3:])

#replace all elements divisible by 3 with -1
arr[arr%3==0] = -1
print(arr)

[[[11 17 94 69 54]
  [31 49 75 32 28]
  [21 95 46  2 47]
  [57 76 64 33 29]]

 [[84 77 25 68 68]
  [58 52 77 66 28]
  [ 4 59 70 68 85]
  [28 32 84 98 43]]

 [[45 54 28 66 76]
  [87 82 20 56 54]
  [94 89 42 51 18]
  [81 70 49 66 61]]]
[[[94 69 54]
  [75 32 28]]

 [[25 68 68]
  [77 66 28]]

 [[28 66 76]
  [20 56 54]]]
[[[11 17 94 -1 -1]
  [31 49 -1 32 28]
  [-1 95 46  2 47]
  [-1 76 64 -1 29]]

 [[-1 77 25 68 68]
  [58 52 77 -1 28]
  [ 4 59 70 68 85]
  [28 32 -1 98 43]]

 [[-1 -1 28 -1 76]
  [-1 82 20 56 -1]
  [94 89 -1 -1 -1]
  [-1 70 49 -1 61]]]


Q10. Work with broadcasting and advanced operations in NumPy.

Create a NumPy array arr of shape (3, 3) with random integers between  1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire array.

In [37]:
import numpy as np

#Random Array of shape(3,3) with range 1 to 21
arr=np.random.randint(1 , 21, size=(3,3))
print(arr)

# Subtract the mean of each row from its respective elements (row-wise normalization).
for i in range(len(arr)):
  print(arr[i]-np.mean(arr[i]))

#Create a new array by squaring all the elements in arr.
print(np.square(arr))

# Find the indices of the top 3 maximum values in the entire array.


[[17  8  9]
 [19  3 17]
 [ 5  1  9]]
[ 5.66666667 -3.33333333 -2.33333333]
[  6. -10.   4.]
[ 0. -4.  4.]
[[289  64  81]
 [361   9 289]
 [ 25   1  81]]
[[13  8 14]
 [ 1  6 14]
 [ 8  8 20]]
[ 1.33333333 -3.66666667  2.33333333]
[-6. -1.  7.]
[-4. -4.  8.]
[[169  64 196]
 [  1  36 196]
 [ 64  64 400]]
